basePath: /api
host: localhost:8080
info:
  contact: {}
  description: API para upload de arquivos
  title: API de Upload de Arquivos
  version: "1.0"
paths:
  /form:
    post:
      consumes:
      - multipart/form-data
      description: Faz upload de múltiplos arquivos
      parameters:
      - collectionFormat: csv
        description: Arquivos para upload (múltiplos)
        in: formData
        items:
          type: file
        name: files
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: Retorna os nomes dos arquivos enviados
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload de arquivos
      tags:
      - uploads
swagger: "2.0"
